# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 408896786e7fc9c3b6d2a2482604a66420dcb0d87f3a2dea5b0d6b11a184330b90f53ae549ffdb323aa563326ccfb3a31d8a165cf52680162a589b615df21d07

test:
  secret_key_base: 1bf34fe3cbd39e93d68dc4e26c28e75bc0592873d60908c8af41d7c4376f742c4ce9ddc8de0d32be93f8fdf72f16c21606965c5278fa5bbacf5668d1d4b7dc8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
